bifrost:
  services:
    - service:
        name: bifrost.services.core.configuration_service.Configuration
        disabled: False
        watchdog_timer_s: 1
        topics:
          request_config_value:
            - 'Reconfiguration_Service.Request'
          utc_timestamp_now:
            - 'Bifrost.Configuration.UTC_Now'
          request_downlink_path:
            - 'Bifrost.Configuration.Downlink_Path'
        stream_declarations:
          Telemetry:
            - 'Telemetry.AOS.Raw.Beef'
            - 'Telemetry.AOS.Raw'

            - 'Telemetry.AOS.VCID.1.TaggedFrame'
            - 'Telemetry.AOS.VCID.2.TaggedFrame'
            - 'Telemetry.AOS.VCID.4.TaggedFrame'
            - 'Telemetry.AOS.VCID.63.TaggedFrame'
            - 'Telemetry.AOS.VCID.Unknown.TaggedFrame'

            - 'Telemetry.AOS.VCID.1.TaggedPacket'
            - 'Telemetry.AOS.VCID.2.TaggedPacket'
            - 'Telemetry.AOS.VCID.4.TaggedPacket'

        key_values:
          global:
            mission:
              pass_id: 0
            paths:
              data_path: '/home/jpluser/products/'
            aws:
              profile: saml-gov
              bucket: ait-test
              region: us-gov-west-1

          instance:
            space_vehicle:
              sv_name: bebop
              sv_identifier: BB
              ccsds_dl_scid: 186

    - service:
        name: bifrost.services.testing.examples.echo.Echo
        disabled: True
        topics:
          echo_alice:
            - Hello.Alice
          echo_bob:
            - Hello.Bob
          echo_mr_x:
            - Hello.Mr_x

    - service: 
        name: bifrost.services.testing.examples.echo.Hello
        disabled: True
        mr_x: Fujiko Mine
        #mr_x: Lupin The Third
        sleep: 10
  
    - service:
        name: bifrost.services.dsn_services.raf_downlink_service.SLE_RAF_Service
        disabled: True
        report_time_s: 5
        autorestart: False
        output_stream: 'Telemetry.AOS.Raw'
        topics:
          directive_stop_sle:
            - 'Bifrost.Directive.SLE.RAF.Stop'
          directive_restart_sle:
            - 'Bifrost.Directive.SLE.RAF.Restart'
        
    - service:
        name: bifrost.services.dsn_services.cltu_uplink_service.SLE_CLTU_Uplink_Service
        disabled: True
        report_time_s: 5
        autorestart: False
        topics:
          directive_stop_sle:
            - 'Bifrost.Directive.SLE.CLTU.Stop'
          directive_restart_sle:
            - 'Bifrost.Directive.SLE.CLTU.Restart'
          uplink:
            - 'Uplink.CmdMetaData.CLTU'
        streams:
          Null

    - service:
        name: bifrost.services.core.web.Web_Server
        disabled: False
        telemetry_stream_pattern: 'Telemetry.AOS.VCID.1.TaggedPacket.>'
        index: '/sunrise/SunRISE-AIT/sunrise/test/'
        downlink_update_pattern: 'Bifrost.Messages.Info.File_Processor.Downlink_Update'
        
    - service:
        name: bifrost.services.core.influx.Influx
        disabled: False
        host_url: http://localhost:8086
        api_token: "IfTvVc7ni-Xipn0GpB3g-oLd5g5lJQh3UarZlS5pRPzCtef4AAP3vdCRpe_QqxS1xBnb_jgEK6WmckBvk6i1ng=="
        org: sunrise
        streams: Null
        topics:
          write_telemetry:
            - 'Telemetry.AOS.VCID.1.TaggedPacket.>'
            - 'Telemetry.AOS.VCID.2.TaggedPacket.>'
          write_command_metadata:
            - Uplink.CmdMetaData.Log

    - service:
        name: bifrost.services.uplink.packet_padder.Packet_Padder
        disabled: False
        topics:
          process:
            - Uplink.CmdMetaData

    - service:
        name: bifrost.services.core.monitoring.Monitor
        disabled: False
        topics:
          process:
            - 'Bifrost.Monitors.>'
        report_time_s: 5


    - service:
        name: bifrost.services.uplink.tctf_service.TCTF_Service
        disabled: False
        topics:
          process:
            - Uplink.CmdMetaData.Padded

    - service:
        name: bifrost.services.sdls_services.sdls_encrypter_service.SDLS_Encrypter_Service
        disabled: False
        report_time_s: 10
        topics:
          process:
            - Uplink.CmdMetaData.TCTF

    - service:
        name: bifrost.services.uplink.ccsds_randomizer_service.CCSDS_Randomizer_Service
        disabled: False
        topics:
          randomize_sdls:
            - Uplink.CmdMetaData.SDLS
          # randomize_tctf:
          # - Uplink.CmdMetaData.TCTF

    - service:
        name: bifrost.services.uplink.CLTU_service.CLTU_Service
        disabled: False
        topics:
          process:
            - Uplink.CmdMetaData.SDLS.Random
            - Uplink.CmdMetaData.TCTF.Random

    - service:
        name: bifrost.services.extra.synchronization_service.Synchronization_Service
        disabled: True
        topics:
          process:
            - create_CLTU

    - service:
        name: bifrost.services.networking.tcp_service.TCP_Manager
        disabled: False
        report_time_s: 10
        topics:
          process:
            - Uplink.CmdMetaData.CLTU

        subscriptions:
          FSW_SIM_Uplink:
            topic: Uplink.CmdMetaData.CLTU
            hostname: fswsim.gdsit.snr.awsgw1.jpl.nasa.gov
            port: 43000
            mode: TRANSMIT
            timeout_seconds: 1

          FSW_SIM_Downlink:
            topic: Telemetry.AOS.Raw.Beef
            hostname: fswsim.gdsit.snr.awsgw1.jpl.nasa.gov
            port: 42403
            mode: RECEIVE
            timeout_seconds: 1

    - service:
        name: bifrost.services.downlink.frame_processors.real_time_processor.RealTime_Telemetry_Frame_Processor
        disabled: False
        topics: Null
        streams:
          process:
            - Telemetry.AOS.VCID.1.TaggedFrame

    - service:
        name: bifrost.services.downlink.frame_processors.stored_processor.Stored_Telemetry_Frame_Processor
        disabled: False
        topics: Null
        streams:
          process:
            - Telemetry.AOS.VCID.2.TaggedFrame

    - service:
        name: sunrise.frame_processors.file_processor.File_Frame_Processor
        disabled: False
        auto_reassemble: True
        topics: Null
        streams:
          process:
            - Telemetry.AOS.VCID.4.TaggedFrame

    - service:
        name: bifrost.services.extra.synchronization_service.Desynchronization_Service
        disabled: False
        topics: Null
        streams:
          desynchronize:
            - Telemetry.AOS.Raw.Beef

    - service:
        name: bifrost.services.testing.data_loss_services.Loss_Service
        disabled: True
        active: False
        percent: 5.25
        announce: False
        topics: Null
        streams:
          process:
            - Telemetry.AOS.Raw.Beef

    - service:
        name: bifrost.services.testing.data_loss_services.Corruption_Service
        disabled: True
        active: False
        percent: 25.25
        announce: False
        topics: Null
        stream:
          process:
            - Telemetry.AOS.Raw.Beef
           
    - service:
        name: bifrost.services.downlink.frame_checks_service.AOS_Frame_Checks_Service
        disabled: False
        topics: Null
        streams:
          process:
            - Telemetry.AOS.Raw

    - service:
        name: bifrost.services.core.commanding.command_loader_service.Command_Loader_Service
        disabled: False
        default_cl_path: ''
        default_uplink_path: ''
        topics:
          show:
            - CL.Show
          execute:
            - CL.Execute
          validate:
            - CL.Validate
          uplink_complete:
            - Uplink.CmdMetaData.Complete           

    - service:
        name: bifrost.services.core.dictionary_services.Command_Dictionary_Service
        disabled: False
        topics:
          generate_command_object:
            - 'Bifrost.Services.Dictionary.Command.Object'
          generate_command_raw: 
            - 'Bifrost.Services.Dictionary.Command.Raw'
            - 'Bifrost.Services.Dictionary.Command.Validate'
          get_dictionary:
            - 'Bifrost.Services.Dictionary.Command.Dictionary'
          get_dictionary_json:
            - 'Bifrost.Services.Dictionary.Command.Json'

    - service:
        name: bifrost.services.downlink.frame_processors.frame_archive_processor.Frame_Archive_Processor
        disabled: False
        frame_ext: .AOSTF
        vcid_interests:
          1: True
          2: False
          4: False
          63: False
        topics: Null
        streams:
          process:
            - 'Telemetry.AOS.VCID.*.TaggedFrame'

    - service:
        name: sunrise.packet_processors.payload_tracker_processor.Payload_Tracker_Service
        disabled: False
        topics:
          process_active_downlink:
            - 'Telemetry.AOS.VCID.1.TaggedPacket.SUNRISE_PAYLOAD_ACTIVE_FILE_DOWNLINK_INFO'
          process_reassembly_report:
            - 'Bifrost.Messages.Info.File_Manager.File_Reassembly_Result'
        active_dl_field_to_filename_regex:
          acknowledge_log:
            - '^acknowledge.*$' 
          cion_watchdog_log:
              - '^cionWatchdog.*$'
          dh_adc_bin:
            - '^dh\.adc.*$'
          dh_bin:
            - '^dh\.bin.*$' 
          dh_log:
            - '^dh\.log.*$'
          dh_spectra_bin:
            - '^dh\.spectra.*$'
          driver_status_log:
            - '^driverstatus.*$'
          dolores_log:
            - '^dolores\.log.*$'
          adc128_sensors_log:
            - '^adc128sensors.*$'
          interface_test_log:
            - '^interface_test\.log.*$'
          obs_nav2_dr_orb_clk_log:
            - '^obsNav2DrOrbClk.*$'
          timesync_udp_log:
            - '^timesync_udp\.log.*$'
          pps_log:
            - '^pps\.log.*$'
          rtgx_postfit_residuals_log:
            - '^rtgxPostfitResiduals\.log.*$'
          rtgx_log:
            - '^rtgx\.log.*$'
          rtgx2_zmq_log:
            - '^rtgx2zmq\.log.*$'
          start_rtgx_log:
            - '^startRtgx\.log.*$'
          startup_log:
            - '^startup\.log.*$'
          rtgx_pos_log_counts:
            - '^rtgx\.pos\.log.*$'
          rtgx_tdp_log:
            - '^rtgx\.tdp\.log.*$'
          system_status_log:
            - '^systemstatus.*$'
          time_server_log:
            - '^time_server\.log.*$'
          tmr_sem_monitor_log:
            - '^tmr_sem_monitor\.log.*$'

    - service:
        name: sunrise.packet_processors.state_of_health_processor.StateOfHealthSubProcessor
        disabled: False
        topics:
          process:
            - 'Telemetry.AOS.VCID.*.TaggedPacket.STATE_OF_HEALTH_MONITOR_STATE_OF_HEALTH_REPORT'
        streams: Null
        announce: True

    - service:
        name: bifrost.services.core.task_manager.task_manager.Task_Manager
        disabled: False
        auto_s3_upload: False
        streams: Null
        topics:
          finalize_s3:
            - S3_File_Upload
          finalize:
            - Untar
            - Bz2_Decompress
            - CSV_to_Influx
          finalize_reassembly:
            - File_Reassembly

        task_transformers:
          # Taskname:
          #   Task Transformer 1:
          #   Task Transformer 2:
          #     filename_filters:
          #       - <Regular Expression>' # Single Quotes
          #     args:
          #        variable1: value
          #        variable2: value
          File_Reassembly:
            S3_File_Upload:
              filename_filters:
                - '.*'

          #   Untar:
          #     filename_filters:
          #       - '^adc128sensors.*\.(tar)$'

          # Untar:
          #   Bz2_Decompress:
          #     filename_filters:
          #       - '^adc128sensors.*\.(bz2)$'

          # Bz2_Decompress:
          #   Post_Process:
          #     filename_filters:
          #       - '^adc128sensors.*[^.]{9}$' # Stop matching to avoid .metadata 
          #     args:
          #       processor:
          #         - adc128sensors

    - service:
        name: bifrost.services.testing.injector_service.Data_Injection_Service
        disabled: False
        topics:
          inject_binary_stream:
            - 'Bifrost.Directive.Data_Injection_Service.Inject_Binary_Stream'

    - service:
        name: bifrost.services.testing.archive_services.Raw_Frame_Archive_Service
        disabled: False
        frame_extension: '.AOS_TF'
        vcid_interests:
          1: True
          2: True
          4: True
          63: False
        streams:
          archive:
            - 'Telemetry.AOS.Raw'

                        
        
